### ISSUE TITLE
Consider using different names for task and extension.

### ISSUE THREAD

**Issue by dougborg** [kt3k/coveralls-gradle-plugin#29]
This is a great plugin, thank you for writing it!

One thing I came across when trying to configure some task dependencies a recent project (https://github.com/ReadyTalk/gradle-readytalk-js), was that you have the extension object and the task for the plugin both using the same name: 'coveralls'. This makes it a bit tricky to configure the task without doing something like this:

```groovy
tasks.coveralls {
  dependsOn 'check'
  onlyIf { isCI }
}
``` 

If I do:

```groovy
coveralls {
  dependsOn 'check'
  onlyIf { isCI }
}
``` 

Gradle thinks I am trying to configure the extension object and barfs out:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/douglas.borg/ReadyTalk/gradle-readytalk-js/build.gradle' line: 73

* What went wrong:
A problem occurred evaluating root project 'gradle-readytalk-js'.
> Could not find method dependsOn() for arguments [check] on root project 'gradle-readytalk-js'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gradle-readytalk-js'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
...
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method dependsOn() for arguments [check] on root project 'gradle-readytalk-js'.
	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_5ou26fne255k0p8hhiq9gu6014$_run_closure9.doCall(/Users/douglas.borg/ReadyTalk/gradle-readytalk-js/build.gradle:73)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_5ou26fne255k0p8hhiq9gu6014.run(/Users/douglas.borg/ReadyTalk/gradle-readytalk-js/build.gradle:72)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 34 more


BUILD FAILED
```

Ideally, I'd like to do something like this:

```groovy
uploadCoveralls {
  dependsOn 'check'
  onlyIf { isCI }
}
```

**Comment by kt3k** [comment]
Sorry, I changed my mind. I like simple `coveralls` task. The workaround is not such ugly or complicated.
